workflows:
  ios-native-workflow:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Distribution API Key
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.koroid.Qrazy-Time
      vars:
        BUNDLE_ID: "com.koroid.Qrazy-Time"
        XCODE_WORKSPACE: "Qrazy-Time.xcworkspace" # <-- Put the name of your Xcode workspace here
        XCODE_SCHEME: "Qrazy-Time" # <-- Put the name of your Xcode scheme here
        APP_STORE_APPLE_ID: 6471254958
      xcode: 14.1
    scripts:
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - koroid@koroidapp.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: false
        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false
